### ISSUE TITLE
use UnetCAM

### ISSUE THREAD

**Issue by wangyf8848** [cenkbircanoglu/isim#31]
how can I train it with Unet instead of DeepLab? Does the code support this?

**Comment by cenkbircanoglu** [comment]
I quickly created a gist for Unet model. I hope it will be helpful. https://gist.github.com/cenkbircanoglu/935ca8714bc38299d65a41c7bcd9d21a

**Comment by wangyf8848** [comment]
Sorry for the late reply. I have tried the code you provided and it is helpful to me. Thank you!
